name: fast_barcode_scanner
description: A fast barcode scanner using MLKit on Android and AVFoundation on iOS.
version: 2.0.0-dev.5
#remove this before we publish
publish_to: none
# homepage: https://github.com/jhoogstraat/fast_barcode_scanner
# repository: https://github.com/jhoogstraat/fast_barcode_scanner

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  fast_barcode_scanner_platform_interface:
    git: https://github.com/tarang1998/fast_barcode_scanner_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.jhoogstraat.fast_barcode_scanner
        pluginClass: FastBarcodeScannerPlugin
      ios:
        pluginClass: FastBarcodeScannerPlugin
